name: flutter_getx_project_template
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # state management
  get: ^5.0.0-release-candidate-9.3.2
  # time zone related 
  flutter_timezone: ^4.1.0
  timezone: ^0.10.1
  intl: ^0.20.2
  # ui related
  skeletonizer: ^2.1.0+1
  flutter_rating_bar: ^4.0.1
  flutter_xlider: ^3.5.0
  connectivity_plus: ^6.1.4
  readmore: ^3.0.0
  # image related
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  flutter_image_compress: ^2.4.0
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  # storage
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4
  # api services
  dio: ^5.8.0+1
  mime: ^2.0.0
  http_parser: ^4.1.2
  pretty_dio_logger: ^1.4.0
  socket_io_client: ^3.1.2
  http: ^1.3.0
  map_location_picker: ^2.0.3

# payment 
  flutter_inappwebview: ^6.0.0-beta.22
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/logo/
    - assets/dev_image/
  # assets:
  #   - images/a_dot_burr.jpeg

  fonts:
    - family: Montaserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
